version: '3.3'

services:
  web:
    build: .
    command: gunicorn movies_admin.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker_admin
      - POSTGRES_PASSWORD=docker_admin
      - POSTGRES_DB=movies
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - web
    ports:
      - "8080:80"

volumes:
  postgres_data:
