version: '3.3'

services:
  etl:
    build: .
    command: python loader.py
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
      - db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch_etl
    volumes:
      - .:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5431
    environment:
      - POSTGRES_USER=docker_admin
      - POSTGRES_PASSWORD=docker_admin
      - POSTGRES_DB=movies

volumes:
  postgres_data: